name: mgn2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.0.2=py37_1
  - python=3.7.7=hcf32534_0_cpython
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - chumpy==0.69
    - cycler==0.10.0
    - dirt==0.3.0
    - gast==0.3.3
    - grpcio==1.28.1
    - h5py==2.10.0
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - matplotlib==3.2.1
    - mock==4.0.2
    - numpy==1.18.3
    - opencv-python==4.2.0.34
    - pillow==7.1.1
    - protobuf==3.11.3
    - psbody-mesh==0.3
    - pyopengl==3.1.5
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - six==1.14.0
    - tensorboard==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.2
    - termcolor==1.1.0
    - werkzeug==1.0.1

